# -*- coding: utf-8 -*-
"""python quiz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IK3xFeWXYPcXw-IROsEXLtBwu6VOfqwC
"""

# python quiz
#This is quiz game of simple python question 
#I'am using tuples for creating questions,options and answers 
#I am using list for guesses because i  will appending gusses  to list


questions=('what is the maximum lenght of python identifier ?:',
           'how is code block indicated in python ?:',
           'which of the following concepts is not a pair of python ?:',
           'which of the following types of loops re not supported in python?:,',
           'which of the following is the proper syntax to check if particular element is present in list?:')
options=(('a.32','b.16','c.128','d.no fixed length is specified'),
         ('a.brackets','b.indentation ','c.key','d.none of the above'),
         ('a.pointers','b.loops','c.dynamic typing ','d.all of the above'),
         ('a.for','b.while','c.do while','d.noneof these'),
         ('a.if ele in list','b.if not ele not in list','c.both A and B','d.none of the above'))

answers=("d","b","a","c","c")
guesses=[]
score=0
question_num=0

for question in questions:
    print('-------------')
    print(question)
    for option in options[question_num]:
        print(option)

    guess= input('enter(a,b,c,d):').lower()
    guesses.append(guess)
    if guess== answers[question_num]:
        score+=1
        print('correct!')
    else:
        print('incorrect!')
        print(f'{answers[question_num]} is the correct answer')
    question_num+=1

print('-----')
print('result')
print('-----')


score=int(score/len(questions)*100)
print(f'your score is :{score}%')

